parser: babel-eslint
parserOptions:
  sourceType: module
env:
  browser: true
  node: true
  es6: true
plugins:
  - prettier
  - flowtype
  - import
extends:
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
  - prettier/react
rules:
  no-duplicate-imports: 0
  import/no-duplicates: 2
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false