extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
env:
  browser: true
  jest: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "react-hooks"
rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "error"
  "react-hooks/rules-of-hooks": "error"
  "react-hooks/exhaustive-deps": "warn"
  prettier/prettier:
    - error