// flow-typed signature: 4f788b8775b879b2145fad310772bd16
// flow-typed version: <<STUB>>/react-leaflet_v^1.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-leaflet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-leaflet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-leaflet/dist/react-leaflet' {
  declare module.exports: any;
}

declare module 'react-leaflet/dist/react-leaflet.min' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/AttributionControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Circle' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/CircleMarker' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/FeatureGroup' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/GeoJSON' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/GridLayer' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/ImageOverlay' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/index' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/LayerGroup' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/LayersControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Map' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/MapComponent' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/MapControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/MapLayer' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Marker' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Pane' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Path' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Polygon' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Polyline' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Popup' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/bounds' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/children' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/controlPosition' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/index' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/latlng' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/latlngList' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/layerContainer' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/map' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/propTypes/viewport' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Rectangle' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/ScaleControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/TileLayer' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/Tooltip' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/WMSTileLayer' {
  declare module.exports: any;
}

declare module 'react-leaflet/lib/ZoomControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/AttributionControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Circle' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/CircleMarker' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/FeatureGroup' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/GeoJSON' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/GridLayer' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/ImageOverlay' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/index' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/LayerGroup' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/LayersControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Map' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/MapComponent' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/MapControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/MapLayer' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Marker' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Pane' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Path' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Polygon' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Polyline' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Popup' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/bounds' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/children' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/controlPosition' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/index' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/latlng' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/latlngList' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/layerContainer' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/map' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/propTypes/viewport' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Rectangle' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/ScaleControl' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/TileLayer' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/Tooltip' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/WMSTileLayer' {
  declare module.exports: any;
}

declare module 'react-leaflet/src/ZoomControl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-leaflet/dist/react-leaflet.js' {
  declare module.exports: $Exports<'react-leaflet/dist/react-leaflet'>;
}
declare module 'react-leaflet/dist/react-leaflet.min.js' {
  declare module.exports: $Exports<'react-leaflet/dist/react-leaflet.min'>;
}
declare module 'react-leaflet/lib/AttributionControl.js' {
  declare module.exports: $Exports<'react-leaflet/lib/AttributionControl'>;
}
declare module 'react-leaflet/lib/Circle.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Circle'>;
}
declare module 'react-leaflet/lib/CircleMarker.js' {
  declare module.exports: $Exports<'react-leaflet/lib/CircleMarker'>;
}
declare module 'react-leaflet/lib/FeatureGroup.js' {
  declare module.exports: $Exports<'react-leaflet/lib/FeatureGroup'>;
}
declare module 'react-leaflet/lib/GeoJSON.js' {
  declare module.exports: $Exports<'react-leaflet/lib/GeoJSON'>;
}
declare module 'react-leaflet/lib/GridLayer.js' {
  declare module.exports: $Exports<'react-leaflet/lib/GridLayer'>;
}
declare module 'react-leaflet/lib/ImageOverlay.js' {
  declare module.exports: $Exports<'react-leaflet/lib/ImageOverlay'>;
}
declare module 'react-leaflet/lib/index.js' {
  declare module.exports: $Exports<'react-leaflet/lib/index'>;
}
declare module 'react-leaflet/lib/LayerGroup.js' {
  declare module.exports: $Exports<'react-leaflet/lib/LayerGroup'>;
}
declare module 'react-leaflet/lib/LayersControl.js' {
  declare module.exports: $Exports<'react-leaflet/lib/LayersControl'>;
}
declare module 'react-leaflet/lib/Map.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Map'>;
}
declare module 'react-leaflet/lib/MapComponent.js' {
  declare module.exports: $Exports<'react-leaflet/lib/MapComponent'>;
}
declare module 'react-leaflet/lib/MapControl.js' {
  declare module.exports: $Exports<'react-leaflet/lib/MapControl'>;
}
declare module 'react-leaflet/lib/MapLayer.js' {
  declare module.exports: $Exports<'react-leaflet/lib/MapLayer'>;
}
declare module 'react-leaflet/lib/Marker.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Marker'>;
}
declare module 'react-leaflet/lib/Pane.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Pane'>;
}
declare module 'react-leaflet/lib/Path.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Path'>;
}
declare module 'react-leaflet/lib/Polygon.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Polygon'>;
}
declare module 'react-leaflet/lib/Polyline.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Polyline'>;
}
declare module 'react-leaflet/lib/Popup.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Popup'>;
}
declare module 'react-leaflet/lib/propTypes/bounds.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/bounds'>;
}
declare module 'react-leaflet/lib/propTypes/children.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/children'>;
}
declare module 'react-leaflet/lib/propTypes/controlPosition.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/controlPosition'>;
}
declare module 'react-leaflet/lib/propTypes/index.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/index'>;
}
declare module 'react-leaflet/lib/propTypes/latlng.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/latlng'>;
}
declare module 'react-leaflet/lib/propTypes/latlngList.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/latlngList'>;
}
declare module 'react-leaflet/lib/propTypes/layerContainer.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/layerContainer'>;
}
declare module 'react-leaflet/lib/propTypes/map.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/map'>;
}
declare module 'react-leaflet/lib/propTypes/viewport.js' {
  declare module.exports: $Exports<'react-leaflet/lib/propTypes/viewport'>;
}
declare module 'react-leaflet/lib/Rectangle.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Rectangle'>;
}
declare module 'react-leaflet/lib/ScaleControl.js' {
  declare module.exports: $Exports<'react-leaflet/lib/ScaleControl'>;
}
declare module 'react-leaflet/lib/TileLayer.js' {
  declare module.exports: $Exports<'react-leaflet/lib/TileLayer'>;
}
declare module 'react-leaflet/lib/Tooltip.js' {
  declare module.exports: $Exports<'react-leaflet/lib/Tooltip'>;
}
declare module 'react-leaflet/lib/WMSTileLayer.js' {
  declare module.exports: $Exports<'react-leaflet/lib/WMSTileLayer'>;
}
declare module 'react-leaflet/lib/ZoomControl.js' {
  declare module.exports: $Exports<'react-leaflet/lib/ZoomControl'>;
}
declare module 'react-leaflet/src/AttributionControl.js' {
  declare module.exports: $Exports<'react-leaflet/src/AttributionControl'>;
}
declare module 'react-leaflet/src/Circle.js' {
  declare module.exports: $Exports<'react-leaflet/src/Circle'>;
}
declare module 'react-leaflet/src/CircleMarker.js' {
  declare module.exports: $Exports<'react-leaflet/src/CircleMarker'>;
}
declare module 'react-leaflet/src/FeatureGroup.js' {
  declare module.exports: $Exports<'react-leaflet/src/FeatureGroup'>;
}
declare module 'react-leaflet/src/GeoJSON.js' {
  declare module.exports: $Exports<'react-leaflet/src/GeoJSON'>;
}
declare module 'react-leaflet/src/GridLayer.js' {
  declare module.exports: $Exports<'react-leaflet/src/GridLayer'>;
}
declare module 'react-leaflet/src/ImageOverlay.js' {
  declare module.exports: $Exports<'react-leaflet/src/ImageOverlay'>;
}
declare module 'react-leaflet/src/index.js' {
  declare module.exports: $Exports<'react-leaflet/src/index'>;
}
declare module 'react-leaflet/src/LayerGroup.js' {
  declare module.exports: $Exports<'react-leaflet/src/LayerGroup'>;
}
declare module 'react-leaflet/src/LayersControl.js' {
  declare module.exports: $Exports<'react-leaflet/src/LayersControl'>;
}
declare module 'react-leaflet/src/Map.js' {
  declare module.exports: $Exports<'react-leaflet/src/Map'>;
}
declare module 'react-leaflet/src/MapComponent.js' {
  declare module.exports: $Exports<'react-leaflet/src/MapComponent'>;
}
declare module 'react-leaflet/src/MapControl.js' {
  declare module.exports: $Exports<'react-leaflet/src/MapControl'>;
}
declare module 'react-leaflet/src/MapLayer.js' {
  declare module.exports: $Exports<'react-leaflet/src/MapLayer'>;
}
declare module 'react-leaflet/src/Marker.js' {
  declare module.exports: $Exports<'react-leaflet/src/Marker'>;
}
declare module 'react-leaflet/src/Pane.js' {
  declare module.exports: $Exports<'react-leaflet/src/Pane'>;
}
declare module 'react-leaflet/src/Path.js' {
  declare module.exports: $Exports<'react-leaflet/src/Path'>;
}
declare module 'react-leaflet/src/Polygon.js' {
  declare module.exports: $Exports<'react-leaflet/src/Polygon'>;
}
declare module 'react-leaflet/src/Polyline.js' {
  declare module.exports: $Exports<'react-leaflet/src/Polyline'>;
}
declare module 'react-leaflet/src/Popup.js' {
  declare module.exports: $Exports<'react-leaflet/src/Popup'>;
}
declare module 'react-leaflet/src/propTypes/bounds.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/bounds'>;
}
declare module 'react-leaflet/src/propTypes/children.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/children'>;
}
declare module 'react-leaflet/src/propTypes/controlPosition.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/controlPosition'>;
}
declare module 'react-leaflet/src/propTypes/index.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/index'>;
}
declare module 'react-leaflet/src/propTypes/latlng.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/latlng'>;
}
declare module 'react-leaflet/src/propTypes/latlngList.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/latlngList'>;
}
declare module 'react-leaflet/src/propTypes/layerContainer.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/layerContainer'>;
}
declare module 'react-leaflet/src/propTypes/map.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/map'>;
}
declare module 'react-leaflet/src/propTypes/viewport.js' {
  declare module.exports: $Exports<'react-leaflet/src/propTypes/viewport'>;
}
declare module 'react-leaflet/src/Rectangle.js' {
  declare module.exports: $Exports<'react-leaflet/src/Rectangle'>;
}
declare module 'react-leaflet/src/ScaleControl.js' {
  declare module.exports: $Exports<'react-leaflet/src/ScaleControl'>;
}
declare module 'react-leaflet/src/TileLayer.js' {
  declare module.exports: $Exports<'react-leaflet/src/TileLayer'>;
}
declare module 'react-leaflet/src/Tooltip.js' {
  declare module.exports: $Exports<'react-leaflet/src/Tooltip'>;
}
declare module 'react-leaflet/src/WMSTileLayer.js' {
  declare module.exports: $Exports<'react-leaflet/src/WMSTileLayer'>;
}
declare module 'react-leaflet/src/ZoomControl.js' {
  declare module.exports: $Exports<'react-leaflet/src/ZoomControl'>;
}
