version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb

    filters:
      branches:
        ignore:
          - gh-pages

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run: 
          name: Run unit tests
          command: |
            npm run build
            npm test
            sed -i -e 's/your_incoming_webhook_url/${WEBHOOK_URL}/g' regconfig.json
            npm run regression
            npm i -D codeclimate-test-reporter
            npx codeclimate-test-reporter < 'coverage/lcov.info'

      - run: 
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "dorayakikun@users.noreply.github.com"
            git config --global user.name dorayakikun
            echo "machine github.com login dorayakikun password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && GIT_USER=dorayakikun npm run publish-gh-pages
